# Generated by Django 4.0.1 on 2022-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('population', models.IntegerField()),
                ('average_age', models.FloatField()),
                ('district_code', models.IntegerField()),
                ('department_code', models.CharField(max_length=25)),
                ('region_code', models.IntegerField()),
                ('region_name', models.CharField(max_length=25)),
            ],
        ),
    ]
